### ISSUE TITLE
Feature Proposal: Notion에서 여러 개의 독립적인 Progress Bar들을 embed하여 사용할 수 있도록 하기

### ISSUE THREAD

**Issue by do0ori** [do0ori/progress-bar#1]
# Problem
- 지금은 Notion에 여러 개의 Progress Bar들을 embed하더라도 상태 관리에 모두 동일한 이름의 local storage key를 사용하기 때문에 사실상 하나의 Progress Bar만 사용 가능하다. 다시 말해, 여러 진행 상황을 동시에 추적할 수 없다.
- Progress Bar를 식별할 수 있는 이름이 없다.

# Proposed Solution
- 사용자로부터 Progress Bar의 이름을 입력받아 설정할 수 있도록 한다.
- 사용자가 입력한 Progress Bar의 이름을 변환하여 key의 postfix로 만드는 방식으로 Progress Bar만의 unique key를 생성하여 식별이 가능하도록 한다.

# Tasks
- [ ] Progress Bar의 이름을 입력받을 수 있는 input field 생성
- [ ] 입력받은 이름을 기반으로 unique key를 생성하는 logic 구현 (같은 이름의 Progress Bar는 상태를 공유)
- [ ] Progress Bar의 이름을 변경하면 기존 key는 삭제할 지 선택 & 새로운 key에 현재 상태를 저장
- [ ] context menu에서 Progress Bar의 이름을 숨길 수 있는 option 추가
- [ ] 추가된 기능을 README.md에 반영
